# Site settings
title: Caitria.
email: caitria.e.oneill@gmail.com
description: "user experience design ux human centered design design thinking design workshop facilitation innovation strategy coaching services from caitria o'neill oneill."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fffbe5 #paleyellow
  secondary: D54A34 #coral
  secondary-dark: 433B28 #mahogany
  tertiary: FFF
  quaternary: 2EB0B9 #turquoise


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/CaitriaONeill
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: All over
  - line: Currently, Amsterdam, NE
  - line: Open to clients all over the world

# Build settings
markdown: kramdown
permalink: pretty
